### ISSUE TITLE
What is the user/password to login the manager page?

### ISSUE THREAD

**Issue by yanglr** [rengert/bolzplatzarena.blog#10]
Hi @rengert @tidyui,
the project [bolzplatzarena.blog](https://github.com/rengert/bolzplatzarena.blog) you are working is awesome.
It is similar to the project [PiranhaCMS](https://github.com/PiranhaCMS)/[piranha.core.templates](https://github.com/PiranhaCMS/piranha.core.templates) and I know it adopted latest `.NET 5`.

But the user/password for the latter is `admin` and `password`, when I tried to used the same credential for manager page when I build and run the code of [bolzplatzarena.blog](https://github.com/rengert/bolzplatzarena.blog), it shows "user name or password is incorrect", could you tell me the password for the user admin? Thanks~

**Comment by rengert** [comment]
The only thing you have to do, is to delete the db file and should be created from the scratch with the default credentials.

I guess the content provided by me is not so important for you, because it is in german.

**Comment by yanglr** [comment]
Yeah, the content I do not need.

I tried just now, I rebuilt after deleted the db file `piranha.blog.db`, however the site cannot accessed now:

![image](https://user-images.githubusercontent.com/3152813/104848581-a3640a00-5920-11eb-9aab-25e2e7705227.png)

Do I need to do extra things to solve it?

**Comment by tidyui** [comment]
@yanglr I’m guessing this is totally in order. If the project doesn’t seed any default data it should return a 404 since there are no pages.

**Comment by yanglr** [comment]
@tidyui @rengert 
OK, so if I want the site to be accessed again and the manager page can be login, what need to do next?
I tried to access `https://localhost:5001/seed`, it does not work. Or should I only clear user related tables in `piranha.blog.db` file?

**Comment by tidyui** [comment]
@yanglr There is no seed in the project. After deleting the database, just log into the manager, create a new Archive as start page and add some posts to it (I'm guessing this is how it's set up @rengert).

Best regards

**Comment by yanglr** [comment]
@tidyui,
Yeah, I tried again. It works now. Thanks~
